### ISSUE TITLE
[BUG]Issue Initialising CPU Usage

### ISSUE THREAD

**Issue by olson339** [mi0bot/OpenHPSDR-Thetis#91] opened 2024-10-14 17:26 UTC
Error occurs during initial startup
Waiting for CPU GetInstance
clears by selecting "ok"
no CPU info displayed at the bottom of Thetis screen

Windows 11
Thetis version  v2.10.3.6 x64 (10/13/24) Beta 6 (MI0BOT)

![Screenshot 2024-10-14 132044](https://github.com/user-attachments/assets/ded4c9b9-c91d-4562-b4a0-6692a35f2f05)
.

**Comment by ramdor** [comment] 2024-10-14 17:30
that will show if there is an issue obtaining the cpu performance profiles. Not a bug, but it is perhaps something to do with your operating system. Closing this.

**Comment by olson339** [comment] 2024-10-14 18:12
Richie
thanks - rebooted PC error resolved

art

**Closed** 2024-10-15 09:27 UTC
Labels: bug
